version: "3.7"
services:
  backoffice-api:
    container_name: backoffice-api
    build:
      context: ./backoffice-api
      dockerfile: Dockerfile
    ports:
      - 3000:8080
  be:
    container_name: be
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - 3001:8080
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: postgres
    ports:
      - 54320:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: be
      MONGO_INITDB_ROOT_PASSWORD: secret123
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
     - "63790:6379"

volumes:
  mongodb_data_container:
  db_data:
